use BD1_PROYECTO2

--------------------TRIGGER [CARRERA]----------------------------------
GO
CREATE TRIGGER bitacorainsert_carrera on CARRERA
AFTER INSERT
AS
BEGIN
	
	INSERT INTO HISTORIAL(fecha,descripcion,tipo) VALUES (GETDATE(),'HUBO UN CAMBIO EN LA TABLA CARRERA','INSERCIÓN')

END
GO

GO
CREATE TRIGGER bitacoradelete_carrera on CARRERA
AFTER DELETE
AS
BEGIN
	
	INSERT INTO HISTORIAL(fecha,descripcion,tipo) VALUES (GETDATE(),'HUBO UN CAMBIO EN LA TABLA CARRERA','ELIMINACION')

END
GO

GO
CREATE TRIGGER bitacoramodificar_carrera on CARRERA
AFTER UPDATE
AS
BEGIN
	
	INSERT INTO HISTORIAL(fecha,descripcion,tipo) VALUES (GETDATE(),'HUBO UN CAMBIO EN LA TABLA CARRERA','MODIFICACION')

END
GO


--------------------TRIGGER [DOCENTE]----------------------------------
GO
CREATE TRIGGER bitacorainsert_docente on DOCENTE
AFTER INSERT
AS
BEGIN
	
	INSERT INTO HISTORIAL(fecha,descripcion,tipo) VALUES (GETDATE(),'HUBO UN CAMBIO EN LA TABLA DOCENTE','INSERCIÓN')

END
GO

GO
CREATE TRIGGER bitacoradelete_docente on DOCENTE
AFTER DELETE
AS
BEGIN
	
	INSERT INTO HISTORIAL(fecha,descripcion,tipo) VALUES (GETDATE(),'HUBO UN CAMBIO EN LA TABLA DOCENTE','ELIMINACION')

END
GO

GO
CREATE TRIGGER bitacoramodificar_docente on DOCENTE
AFTER UPDATE
AS
BEGIN
	
	INSERT INTO HISTORIAL(fecha,descripcion,tipo) VALUES (GETDATE(),'HUBO UN CAMBIO EN LA TABLA DOCENTE','MODIFICACION')

END
GO


--------------------TRIGGER [ESTUDIANTE]----------------------------------
GO
CREATE TRIGGER bitacorainsert_estudiante on ESTUDIANTE
AFTER INSERT
AS
BEGIN
	
	INSERT INTO HISTORIAL(fecha,descripcion,tipo) VALUES (GETDATE(),'HUBO UN CAMBIO EN LA TABLA ESTUDIANTE','INSERCIÓN')

END
GO

GO
CREATE TRIGGER bitacoradelete_estudiante on ESTUDIANTE
AFTER DELETE
AS
BEGIN
	
	INSERT INTO HISTORIAL(fecha,descripcion,tipo) VALUES (GETDATE(),'HUBO UN CAMBIO EN LA TABLA ESTUDIANTE','ELIMINACION')

END
GO

GO
CREATE TRIGGER bitacoramodificar_estudiante on ESTUDIANTE
AFTER UPDATE
AS
BEGIN
	
	INSERT INTO HISTORIAL(fecha,descripcion,tipo) VALUES (GETDATE(),'HUBO UN CAMBIO EN LA TABLA ESTUDIANTE','MODIFICACION')

END
GO


--------------------TRIGGER [CURSO]----------------------------------
GO
	CREATE TRIGGER bitacorainsert_curso on CURSO
	AFTER INSERT
	AS
	BEGIN
	
		INSERT INTO HISTORIAL(fecha,descripcion,tipo) VALUES (GETDATE(),'HUBO UN CAMBIO EN LA TABLA CURSO','INSERCIÓN')

	END
GO

GO
	CREATE TRIGGER bitacoradelete_curso on CURSO
	AFTER DELETE
	AS
	BEGIN
	
		INSERT INTO HISTORIAL(fecha,descripcion,tipo) VALUES (GETDATE(),'HUBO UN CAMBIO EN LA TABLA CURSO','ELIMINACION')

	END
GO

GO
	CREATE TRIGGER bitacoramodificar_curso on CURSO
	AFTER UPDATE
	AS
	BEGIN
	
		INSERT INTO HISTORIAL(fecha,descripcion,tipo) VALUES (GETDATE(),'HUBO UN CAMBIO EN LA TABLA CURSO','MODIFICACION')

	END
GO

--------------------TRIGGER [ACTA]----------------------------------
GO
	CREATE TRIGGER bitacorainsert_acta on ACTA
	AFTER INSERT
	AS
	BEGIN
	
		INSERT INTO HISTORIAL(fecha,descripcion,tipo) VALUES (GETDATE(),'HUBO UN CAMBIO EN LA TABLA ACTA','INSERCIÓN')

	END
GO

GO
	CREATE TRIGGER bitacoradelete_acta on ACTA
	AFTER DELETE
	AS
	BEGIN
	
		INSERT INTO HISTORIAL(fecha,descripcion,tipo) VALUES (GETDATE(),'HUBO UN CAMBIO EN LA TABLA ACTA','ELIMINACION')

	END
GO

GO
	CREATE TRIGGER bitacoramodificar_acta on ACTA
	AFTER UPDATE
	AS
	BEGIN
	
		INSERT INTO HISTORIAL(fecha,descripcion,tipo) VALUES (GETDATE(),'HUBO UN CAMBIO EN LA TABLA ACTA','MODIFICACION')

	END
GO

--------------------TRIGGER [ASIGNACION_CURSO]----------------------------------
GO
	CREATE TRIGGER bitacorainsert_asignacion_curso on ASIGNACION_CURSO
	AFTER INSERT
	AS
	BEGIN
	
		INSERT INTO HISTORIAL(fecha,descripcion,tipo) VALUES (GETDATE(),'HUBO UN CAMBIO EN LA TABLA ASIGNACION_CURSO','INSERCIÓN')

	END
GO

GO
	CREATE TRIGGER bitacoradelete_asignacion_curso on ASIGNACION_CURSO
	AFTER DELETE
	AS
	BEGIN
	
		INSERT INTO HISTORIAL(fecha,descripcion,tipo) VALUES (GETDATE(),'HUBO UN CAMBIO EN LA TABLA ASIGNACION_CURSO','ELIMINACION')

	END
GO

GO
	CREATE TRIGGER bitacoramodificar_asignacion_curso on ASIGNACION_CURSO
	AFTER UPDATE
	AS
	BEGIN
	
		INSERT INTO HISTORIAL(fecha,descripcion,tipo) VALUES (GETDATE(),'HUBO UN CAMBIO EN LA TABLA ASIGNACION_CURSO','MODIFICACION')

	END
GO

--------------------TRIGGER [DESASIGNACION_CURSO]----------------------------------
GO
	CREATE TRIGGER bitacorainsert_desasignacion_curso on DESASIGNACION_CURSO
	AFTER INSERT
	AS
	BEGIN
	
		INSERT INTO HISTORIAL(fecha,descripcion,tipo) VALUES (GETDATE(),'HUBO UN CAMBIO EN LA TABLA DESASIGNACION_CURSO','INSERCIÓN')

	END
GO

GO
	CREATE TRIGGER bitacoradelete_desasignacion_curso on DESASIGNACION_CURSO
	AFTER DELETE
	AS
	BEGIN
	
		INSERT INTO HISTORIAL(fecha,descripcion,tipo) VALUES (GETDATE(),'HUBO UN CAMBIO EN LA TABLA DESASIGNACION_CURSO','ELIMINACION')

	END
GO

GO
	CREATE TRIGGER bitacoramodificar_desasignacion_curso on DESASIGNACION_CURSO
	AFTER UPDATE
	AS
	BEGIN
	
		INSERT INTO HISTORIAL(fecha,descripcion,tipo) VALUES (GETDATE(),'HUBO UN CAMBIO EN LA TABLA DESASIGNACION_CURSO','MODIFICACION')

	END
GO

--------------------TRIGGER [CURSO_HABILITADO]----------------------------------
GO
	CREATE TRIGGER bitacorainsert_curso_habilitado on CURSO_HABILITADO
	AFTER INSERT
	AS
	BEGIN
	
		INSERT INTO HISTORIAL(fecha,descripcion,tipo) VALUES (GETDATE(),'HUBO UN CAMBIO EN LA TABLA CURSO_HABILITADO','INSERCIÓN')

	END
GO

GO
	CREATE TRIGGER bitacoradelete_curso_habilitado on CURSO_HABILITADO
	AFTER DELETE
	AS
	BEGIN
	
		INSERT INTO HISTORIAL(fecha,descripcion,tipo) VALUES (GETDATE(),'HUBO UN CAMBIO EN LA TABLA CURSO_HABILITADO','ELIMINACION')

	END
GO

GO
	CREATE TRIGGER bitacoramodificar_curso_habilitado on CURSO_HABILITADO
	AFTER UPDATE
	AS
	BEGIN
	
		INSERT INTO HISTORIAL(fecha,descripcion,tipo) VALUES (GETDATE(),'HUBO UN CAMBIO EN LA TABLA CURSO_HABILITADO','MODIFICACION')

	END
GO

--------------------TRIGGER [HORARIO]----------------------------------
GO
	CREATE TRIGGER bitacorainsert_horario on HORARIO
	AFTER INSERT
	AS
	BEGIN
	
		INSERT INTO HISTORIAL(fecha,descripcion,tipo) VALUES (GETDATE(),'HUBO UN CAMBIO EN LA TABLA HORARIO','INSERCIÓN')

	END
GO

GO
	CREATE TRIGGER bitacoradelete_horario on HORARIO
	AFTER DELETE
	AS
	BEGIN
	
		INSERT INTO HISTORIAL(fecha,descripcion,tipo) VALUES (GETDATE(),'HUBO UN CAMBIO EN LA TABLA HORARIO','ELIMINACION')

	END
GO

GO
	CREATE TRIGGER bitacoramodificar_horario on HORARIO
	AFTER UPDATE
	AS
	BEGIN
	
		INSERT INTO HISTORIAL(fecha,descripcion,tipo) VALUES (GETDATE(),'HUBO UN CAMBIO EN LA TABLA HORARIO','MODIFICACION')

	END
GO


--------------------TRIGGER [NOTAS_ESTUDIANTE]----------------------------------
GO
	CREATE TRIGGER bitacorainsert_notas_estudiante on NOTAS_ESTUDIANTE
	AFTER INSERT
	AS
	BEGIN
	
		INSERT INTO HISTORIAL(fecha,descripcion,tipo) VALUES (GETDATE(),'HUBO UN CAMBIO EN LA TABLA NOTAS_ESTUDIANTE','INSERCIÓN')

	END
GO

GO
	CREATE TRIGGER bitacoradelete_notas_estudiante on NOTAS_ESTUDIANTE
	AFTER DELETE
	AS
	BEGIN
	
		INSERT INTO HISTORIAL(fecha,descripcion,tipo) VALUES (GETDATE(),'HUBO UN CAMBIO EN LA TABLA NOTAS_ESTUDIANTE','ELIMINACION')

	END
GO

GO
	CREATE TRIGGER bitacoramodificar_notas_estudiante on NOTAS_ESTUDIANTE
	AFTER UPDATE
	AS
	BEGIN
	
		INSERT INTO HISTORIAL(fecha,descripcion,tipo) VALUES (GETDATE(),'HUBO UN CAMBIO EN LA TABLA NOTAS_ESTUDIANTE','MODIFICACION')

	END
GO




